export const allData = [
  {
    member: 'Darlene Robertson1',
    id: 1,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 6,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 7,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 8,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 9,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 10,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 6,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 7,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 8,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 9,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson',
    id: 10,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson2',
    id: 2,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson3',
    id: 3,
    joined: '4 May 2022',
    editor: false,
    action: ':',
  },
  {
    member: 'Darlene Robertson4',
    id: 4,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
  {
    member: 'Darlene Robertson5',
    id: 5,
    joined: '4 May 2022',
    editor: true,
    action: ':',
  },
];
